"use client";import Link from"next/link";import{useMemo,useState}from"react";
const sections=[
["Quick start","Register, verify your email, sign in, and complete onboarding. Your default organization is created automatically."],
["Authentication","Dashboard requests use rotating secure HttpOnly cookies. SDKs use scoped TokenWatch keys, never login JWTs."],
["Node SDK",`import {TokenWatch} from "@tokenwatch/sdk"; const tw=new TokenWatch({apiKey:process.env.TOKENWATCH_API_KEY});`],
["Python SDK",`from tokenwatch import TokenWatch; tw=TokenWatch(os.environ["TOKENWATCH_API_KEY"])`],
["REST integration",`curl -X POST "$TOKENWATCH_API/v1/ingest/usage" -H "X-TokenWatch-Key: $TOKENWATCH_API_KEY" -H "Content-Type: application/json" -d @event.json`],
["Usage ingestion","Send provider, model, prompt_tokens, completion_tokens, a unique idempotency_key, and a recent timestamp. TokenWatch calculates cost server-side."],
["Policy check","POST /policy/check with provider, model, and estimated tokens returns allowed, blocked, reason, remaining_budget, and current_usage."],
["Errors","401 means credentials are unavailable; 403 means permission denied; 402/409 indicate plan limits; 422 is validation; 429 includes Retry-After."],
["Pagination","List APIs accept page and page_size up to 100 and return items plus pagination metadata."],
["SDK-key rotation","Rotate a key to revoke the old secret immediately and receive a new one-time secret."],
["Support","Check /status first, preserve the X-Request-ID response header, then contact support without sharing credentials."],
] as const;
export default function Docs(){const[q,setQ]=useState("");const shown=useMemo(()=>sections.filter(([t,b])=>(t+" "+b).toLowerCase().includes(q.toLowerCase())),[q]);return <main className="min-h-screen bg-slate-50"><header className="border-b bg-white"><div className="mx-auto flex max-w-6xl justify-between px-6 py-4"><Link href="/" className="font-bold">TokenWatch Docs</Link><div className="flex gap-4 text-sm"><Link href="/help">Help</Link><a href="https://tokenwatch-backend.vercel.app/docs">OpenAPI</a></div></div></header><div className="mx-auto max-w-4xl px-6 py-12"><h1 className="text-4xl font-semibold">Integrate TokenWatch</h1><p className="mt-3 text-slate-600">Production API: <code>https://tokenwatch-backend.vercel.app</code></p><label className="mt-8 block font-medium" htmlFor="doc-search">Search documentation</label><input id="doc-search" type="search" value={q} onChange={e=>setQ(e.target.value)} placeholder="Search SDKs, errors, authentication…" className="mt-2 w-full rounded-xl border bg-white p-4"/><p aria-live="polite" className="mt-2 text-sm text-slate-500">{shown.length} topics</p><div className="mt-10 space-y-10">{shown.map(([title,body])=><section id={title.toLowerCase().replaceAll(" ","-")} key={title}><h2 className="text-2xl font-semibold">{title}</h2>{/[/{]|curl|import |from /.test(body)?<pre className="mt-4 overflow-x-auto rounded-xl bg-slate-950 p-4 text-sm text-cyan-200"><code>{body}</code></pre>:<p className="mt-3 leading-7 text-slate-600">{body}</p>}</section>)}</div></div></main>}
