"use client";

import { useEffect, useState } from "react";
import { toast } from "sonner";
import { createBillingPortal, createCheckout, getBillingPlans, getBillingSummary } from "@/lib/api";
import { useWorkspace } from "@/components/app-shell";
import { Card, PageHeader } from "@/components/page-header";

type Plan={code:string;name:string;description:string;monthly_price:number;annual_price:number;entitlements:Record<string,number|boolean>};
type Invoice={id:string;number?:string;status:string;currency:string;total:number;amount_paid:number;hosted_invoice_url?:string;created_at:string};
type Summary={subscription?:{status:string;current_period_end?:string;cancel_at_period_end:boolean;plans?:{name:string}};entitlements:{plan:{name:string};usage:{request_count:number;token_count:number;cost:number};limits:Record<string,number>};invoices:Invoice[]};

export default function BillingPage(){
 const {organization,role}=useWorkspace(); const [plans,setPlans]=useState<Plan[]>([]); const [summary,setSummary]=useState<Summary|null>(null); const [busy,setBusy]=useState("");
 useEffect(()=>{getBillingPlans().then(r=>setPlans(r.data)).catch(()=>toast.error("Could not load plans"))},[]);
 useEffect(()=>{if(organization)getBillingSummary(organization.id).then(r=>setSummary(r.data)).catch(()=>toast.error("Could not load billing"))},[organization]);
 async function checkout(code:string){if(!organization)return;setBusy(code);try{const r=await createCheckout(organization.id,code);window.location.assign(r.data.url)}catch(e){toast.error(e instanceof Error?e.message:"Checkout unavailable")}finally{setBusy("")}}
 async function portal(){if(!organization)return;setBusy("portal");try{const r=await createBillingPortal(organization.id);window.location.assign(r.data.url)}catch(e){toast.error(e instanceof Error?e.message:"Portal unavailable")}finally{setBusy("")}}
 const current=summary?.subscription?.plans?.name||summary?.entitlements.plan.name||"Free"; const limits=summary?.entitlements.limits||{}; const usage=summary?.entitlements.usage;
 return <div className="space-y-6"><PageHeader title="Billing" description="Manage your subscription, usage limits, invoices, and secure billing portal."/>
 <Card><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm text-slate-500">Current plan</p><p className="mt-1 text-2xl font-semibold">{current}</p><p className="mt-1 text-sm capitalize text-slate-500">{summary?.subscription?.status||"Free tier"}{summary?.subscription?.current_period_end?` · renews ${new Date(summary.subscription.current_period_end).toLocaleDateString()}`:""}</p></div>{summary?.subscription&&<button disabled={busy==="portal"||role!=="owner"} onClick={portal} className="rounded-lg bg-slate-900 px-4 py-2 text-sm text-white disabled:opacity-50">Open billing portal</button>}</div></Card>
 <div className="grid gap-4 sm:grid-cols-3"><Card><p className="text-sm text-slate-500">Requests this month</p><p className="mt-2 text-xl font-semibold">{Number(usage?.request_count||0).toLocaleString()} / {limits.monthly_requests===-1?"Unlimited":Number(limits.monthly_requests||0).toLocaleString()}</p></Card><Card><p className="text-sm text-slate-500">Tokens this month</p><p className="mt-2 text-xl font-semibold">{Number(usage?.token_count||0).toLocaleString()} / {limits.monthly_tokens===-1?"Unlimited":Number(limits.monthly_tokens||0).toLocaleString()}</p></Card><Card><p className="text-sm text-slate-500">Spend this month</p><p className="mt-2 text-xl font-semibold">${Number(usage?.cost||0).toFixed(2)} / {limits.monthly_spend===-1?"Unlimited":`$${Number(limits.monthly_spend||0).toFixed(2)}`}</p></Card></div>
 <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{plans.map(p=><Card key={p.code}><h2 className="text-xl font-semibold">{p.name}</h2><p className="mt-1 min-h-10 text-sm text-slate-500">{p.description}</p><p className="mt-3 text-3xl font-semibold">{p.code==="enterprise"?"Custom":`$${p.monthly_price}`} {p.code!=="enterprise"&&<span className="text-sm font-normal text-slate-500">/month</span>}</p><p className="mt-3 text-sm text-slate-600">{p.entitlements.monthly_requests===-1?"Unlimited":Number(p.entitlements.monthly_requests).toLocaleString()} monthly requests · {p.entitlements.members===-1?"Unlimited":p.entitlements.members} members</p>{["starter","pro","team"].includes(p.code)&&<button disabled={busy!==""||role!=="owner"||current===p.name} onClick={()=>checkout(p.code)} className="mt-5 rounded-lg bg-slate-900 px-4 py-2 text-sm text-white disabled:opacity-50">{current===p.name?"Current plan":busy===p.code?"Opening checkout…":"Choose plan"}</button>}</Card>)}</div>
 <Card><h2 className="text-lg font-semibold">Invoices</h2><div className="mt-4 overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b"><th className="py-2">Invoice</th><th>Status</th><th>Total</th><th>Date</th><th></th></tr></thead><tbody>{summary?.invoices.map(i=><tr className="border-b last:border-0" key={i.id}><td className="py-3">{i.number||"Invoice"}</td><td className="capitalize">{i.status}</td><td>{i.currency} {Number(i.total).toFixed(2)}</td><td>{new Date(i.created_at).toLocaleDateString()}</td><td>{i.hosted_invoice_url&&<a className="text-blue-600" href={i.hosted_invoice_url} target="_blank" rel="noreferrer">View</a>}</td></tr>)}{!summary?.invoices.length&&<tr><td className="py-4 text-slate-500" colSpan={5}>No invoices yet.</td></tr>}</tbody></table></div></Card></div>
}
